### ISSUE TITLE
Pin stripping

### ISSUE THREAD

**Issue by stratochief66** [Pingopete/RVE-KSP-0.90#10]
I have proposed a change to drastically reduce the appearance of black stripes across the lower layer of clouds.

Given the solution, which was increasing the displacement of the low clouds from the ground, it looks to me like the source of the pin stripping is difficulty of an engine distinguishing between closely placed layers. I am not sure what was fighting with the clouds, possibly multiple cloud sizes or layers in the low cloud layer?

Anyway, perhaps by displacing the ground textures or city light textures slightly from the ground might help with the visual glitches?

At the least, perhaps raising the city light texture altitude would be a good place to test this. 

The EVE cfg files allowed the altitude of the city lights to be modified. but I do not find it clear if that is or isn't possible with the RVE config file. Would some RVE / EVE Manager element need to be modified or recompiled to change that value?

**Comment by Pingopete** [comment]
Were you looking at a 7.4 EVE config (or prior)? The new Overhauls wrap city/ground textures to the PQS terrain and there is no exposed command or option in the configs to adjust this. Like you said, it'd require a change in the EVE .dll's

**Comment by Pingopete** [comment]
RVE version surpassed and no longer under development

**Comment by stratochief66** [comment]
@Pingopete 

Haha, wow. After so many months both of us look at this Issue on the same day. I was just testing out:
https://github.com/Pingopete/RVE-KSP-1.0.4

With the change of making the clouds higher and finding that improves the cloud and general appearance during ascent for me.

I had to do so outside of the game, direct to the clouds.cfg

Is there a way to modify the cloud properties in game with KSP 1.0.4 ? I no longer seem to have that ability.

**Comment by Pingopete** [comment]
Sorry, that version uses outdated .dlls for a number of different reasons, one of the downsides is that the GUI no longer works, changes can still be made in the configs out of the game though yes. And sorry, about the pin striping, yeah it would appear a linux/opengl manifestation of the same issue affecting windows slightly differently, I _think_ it should be fixable with camera distances. It seems to be more noticeable on larger planets with relatively closer spheres (clouds) than in stock ksp sized planets
